(* ::Package:: *)

(* ::Input:: *)
(*radii = <|Sun->2.84,Mercury->0.38,Venus->0.78,Earth->0.81,Mars->.53,Jupiter->1.7,Saturn->1.4,Uranus->1.1,Neptune->1.1,Pluto->0.1|>;*)
(*distance = <|Sun->0,Mercury->4.76,Venus->9.45,Earth->14.07,Mars->18.97,Jupiter->24.71,Saturn->30.52,Uranus->36.68,Neptune->42.89,Pluto->49.55|>;*)
(**)
(*sun = {Orange,Specularity[White,7],Sphere[{0,0,0},radii[Sun]]};*)
(**)
(*mercury = Sphere[{distance[Mercury],0,0},radii[Mercury]];*)
(*venus = Sphere[{distance[Venus],0,0},radii[Venus]];*)
(*earth = Sphere[{distance[Earth],0,0},radii[Earth]];*)
(*mars = Sphere[{distance[Mars],0,0},radii[Mars]];*)
(*jupiter = Sphere[{distance[Jupiter],0,0},radii[Jupiter]];*)
(*saturn = Sphere[{distance[Saturn],0,0},radii[Saturn]];*)
(*uranus = Sphere[{distance[Uranus],0,0},radii[Uranus]];*)
(*neptune = Sphere[{distance[Neptune],0,0},radii[Neptune]];*)
(*pluto = Sphere[{distance[Pluto],0,0},radii[Pluto]];*)
(**)
(**)
(*Graphics3D[{sun,mercury,venus,earth,mars,jupiter,saturn,uranus,neptune,pluto}]*)
(**)
