(* ::Package:: *)

(* ::Input:: *)
(*radii = <|Sun->2.84,Mercury->0.38,Venus->0.78,Earth->0.81,Mars->.53,Jupiter->1.7,Saturn->1.4,Uranus->1.1,Neptune->1.1,Pluto->0.1|>;*)
(*distance = <|Sun->0,Mercury->4.76,Venus->9.45,Earth->14.07,Mars->18.97,Jupiter->24.71,Saturn->30.52,Uranus->36.68,Neptune->42.89,Pluto->49.55|>;*)
(*orbitLength = <|Mercury->1/4,Venus->7/12,Earth->1,Mars->23/12,Jupiter->142/12,Saturn->354/12,Uranus->1009/12,Neptune->1979/12,Pluto->2977/12|>;*)
(**)
(**)
(*sun = {Orange,Specularity[White,7],Sphere[{0,0,0},radii[Sun]]};*)
(*mercury[t_] := {Red, Sphere[{Cos[2Pi*t/orbitLength[Mercury]]*distance[Mercury],Sin[2Pi*t/orbitLength[Mercury]]*distance[Mercury],0},radii[Mercury]]};*)
(*venus[t_] := Sphere[{Cos[2Pi*t/orbitLength[Venus]]*distance[Venus],Sin[2Pi*t/orbitLength[Venus]]*distance[Venus],0},radii[Venus]];*)
(*earth[t_] := Sphere[{Cos[2Pi*t]*distance[Earth],Sin[2Pi*t]*distance[Earth],0},radii[Earth]];*)
(*mars[t_] := Sphere[{Cos[2Pi*t/orbitLength[Mars]]*distance[Mars],Sin[2Pi*t/orbitLength[Mars]]*distance[Mars],0},radii[Mars]];*)
(*jupiter[t_] := Sphere[{Cos[2Pi*t/orbitLength[Jupiter]]*distance[Jupiter],Sin[2Pi*t/orbitLength[Jupiter]]*distance[Jupiter],0},radii[Jupiter]];*)
(*saturn [t_] := Sphere[{Cos[2Pi*t/orbitLength[Saturn]]*distance[Saturn],Sin[2Pi*t/orbitLength[Saturn]]*distance[Saturn],0},radii[Saturn]];*)
(*uranus [t_] := Sphere[{Cos[2Pi*t/orbitLength[Uranus]]*distance[Uranus],Sin[2Pi*t/orbitLength[Uranus]]*distance[Uranus],0},radii[Uranus]];*)
(*neptune [t_] := Sphere[{Cos[2Pi*t/orbitLength[Neptune]]*distance[Neptune],Sin[2Pi*t/orbitLength[Neptune]]*distance[Neptune],0},radii[Neptune]];*)
(*pluto [t_] := Sphere[{Cos[2Pi*t/orbitLength[Pluto]]*distance[Pluto],Sin[2Pi*t/orbitLength[Pluto]]*distance[Pluto],0},radii[Pluto]];*)
(**)
(**)
(**)
(**)
(*Manipulate[Graphics3D[{sun,mercury[t],venus[t],earth[t],mars[t],jupiter[t],saturn[t],uranus[t],neptune[t],pluto[t]},Background->Black,Boxed->False,ImageSize->Full,PlotRange->{{-50,50},{-50,50},{-5,5}}],{{t,2015,"Earth Years"},2015,2069,ControlType->Animator,AnimationRate->.3,RefreshRate->60,Appearance->"Labeled"}]*)
(**)


(* ::Input:: *)
(**)
